print("==============================================")
print("My Name is Kumsa Mergia :")
print("I am DevOps Engineer")
print("I Love Automation")
print("=============== Thank You ====================")
